export const ADD_CREATURES = 'ADD_CREATURES';
export const ADD_CREATURES_SAGA = 'ADD_CREATURES_SAGA';
export const FIND_CREATURE = 'FIND_CREATURE';
export const FIND_CREATURE_SAGA = 'FIND_CREATURE_SAGA';
